######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 9 22:39:33 2011
######################################################################

QT += declarative opengl

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
