# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       qmlcalc

# >> macros
# << macros

Summary:    MeeGo QML Harmattan-esque calculator
Version:    0.1.0
Release:    1
Group:      Applications/System
License:    LGPL v2.1
URL:        http://github.com/nemomobile/qmlcalc
Source0:    %{name}-%{version}.tar.bz2
Source100:  qmlcalc.yaml
Requires:   qt-components-qt5
Requires:   mapplauncherd-booster-qtcomponents-qt5
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(qdeclarative5-boostable)
BuildRequires:  desktop-file-utils

%description
Calculator application written using QML


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/qmlcalc
%{_datadir}/applications/qmlcalc.desktop
%{_datadir}/qmlcalc/*
# >> files
# << files
